config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root 'home#index'

  resources :dashboard, only: [:index]
  resources :likeable_content

  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  namespace :api do
    get 'total_likes/:identifier/:api_token', to: 'api#total_likes'
    post 'likes/:identifier/:api_token', to: 'api#create_like'
  end
end

app/models/likeable_content.rb
class LikeableContent
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :identifier, type: String

  before_create :create_unique_identifier

  belongs_to :user
  embeds_many :likes

  validates :title, presence: true

  private

  def create_unique_identifier
    self.identifier = generate_uuid
  end

  def generate_uuid
    SecureRandom.uuid
  end

  def self.find_by_identifier(unique_identifier)
    where(identifier: unique_identifier).first
  end
end

app/controllers/likeable_content_controller.rb
class LikeableContentController < ApplicationController
  before_action :authenticate_user!

  def new
    @content = LikeableContent.new
  end

  def show
    @content = LikeableContent.find(params[:id])

    unless authorised_content(@content)
      @content = nil
      flash[:error] = 'Page Does Not Exist'
      redirect_to dashboard_index_path
    end
  end

  def create
    content = current_user.likeable_contents.create(content_params)

    if content.save
      flash[:success] = 'Content Saved'
      redirect_to likeable_content_path(content)
    else
      flash.now[:error] = 'Content Not Saved'
      render :new
    end
  end

  def update
    content = LikeableContent.find(params[:id])

    unless authorised_content(content)
      content = nil
      flash[:error] = 'Content Does Not Exist'
      redirect_to dashboard_index_path and return
    end

    if content.update_attributes(content_params)
      flash[:success] = 'Content Updated'
      redirect_to likeable_content_path(content)
    else
      flash[:error] = 'Content Not Updated'
      render :edit
    end
  end

  private

  def content_params
    params.require(:likeable_content).permit(:id, :title, :description)
  end

  def authorised_content(content)
    content.user_id == current_user.id
  end
end

app/helpers/likeable_content_helper.rb
module LikeableContentHelper
end

app/views/likeable_content/edit.html.erb
edit.html.erb

app/views/likeable_content/new.html.erb
<h1>Add New Content</h1>

<%= form_for :likeable_content, url: likeable_content_index_path do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/likeable_content/show.html.erb
<h1><%= @content.title %></h1>
<ul>
  <li><%= link_to 'Back to Dashboard', dashboard_index_path %></li>
</ul>
<p>Description: <%= @content.description %></p>
<p>Identifier: <%= @content.identifier %></p>
<p>Likes: <%= @content.likes.count %></p>